# The specific version that we aim at installing.
# If we wanted to get whatever is the latest not
# marked as a release candidate we could instead
# not specify a version but simply `docker-ce`.
docker_version_number: "18.03.0"
docker_version: "{{ docker_version_number }}~ce-0~ubuntu"
# docker_edition: "ce"
# docker_version: "18.04.0"
# docker_apt_package_name: "{{ docker_version }}~{{ docker_edition }}~3-0~{{ ansible_distribution | lower }}"
#

docker_bin: /usr/bin/docker

# The release channel to look for packages.
# If your curious about what are the channels and which
# versions do they have, head to
# https://download.docker.com/linux/ubuntu/dists/zesty/ (or
# any other distro you want).
docker_apt_release_channel: 'stable'

# The URL of the apt repository.
# Here we're picking the values from the knowledge
# that ansible already took from the system. This way
# we can make fewer changes in this code when changing
# from one distro to another.
# Note that there's a compatibility matrix but in general
# new versions of Ubuntu are well covered.
docker_apt_repository: 'deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}'

docker_compose_version: 1.21.2

docker_compose_bin: /usr/local/bin/docker-compose

docker_compose_as_root: yes
