version: '3.5'

services:
  frontend:
    user: "2000:2000"
    image: $REGISTRY_URL/tike/eduviewer-frontend:$DOCKER_TAG
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./certs/ssl.crt:${CERT_PATH}
      - ./certs/ssl.key:${KEY_PATH}
    networks:
      - app
      - default
    environment:
      - SERVER_NAME=$SERVER_NAME
      - CERT_PATH=$CERT_PATH
      - KEY_PATH=$KEY_PATH
    command: /bin/sh -c "envsubst '$${SERVER_NAME},$${CERT_PATH},$${KEY_PATH}' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  app:
    external:
      name: app
