---

- name: Create SSL cert bundle
  shell: cat {{ ssl_cert_path }} {{ ca_bundle_path }} > {{ ssl_cert_bundle_path }}

- name: Copy certs & keys to application-scoped certs subdir
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: eduviewer
    group: eduviewer
    remote_src: yes
  loop:
    - { src: "{{ ssl_key_path }}", dest: "{{ eduviewer_base_dir }}/certs/ssl.key" }
    - { src: "{{ ssl_cert_bundle_path }}", dest: "{{ eduviewer_base_dir }}/certs/ssl.crt" }
