---

- name: Add the neccessary eduviewer group
  group:
    name: eduviewer
    state: present
    gid: 2000
  become: true

- name: Create eduviewer user
  user:
    name: eduviewer
    group: eduviewer
    uid: 2000
    comment: User for Eduviewer application
    state: present
  become: true

- name: Create frontend app dir
  file:
    path: "{{ eduviewer_base_dir }}"
    owner: eduviewer
    group: eduviewer
    state: directory
    mode: 0775
  become: true

- name: Create certs directory
  file:
    path: "{{ eduviewer_base_dir }}/certs"
    owner: eduviewer
    group: eduviewer
    state: directory
    mode: 0775
